# Generated by Django 4.1.4 on 2023-04-06 03:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=20, verbose_name='last name')),
                ('first_name', models.CharField(max_length=20, verbose_name='first name')),
                ('mid_name', models.CharField(blank=True, max_length=20, verbose_name='mid name')),
                ('Tel', models.CharField(max_length=20, verbose_name='telephone')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_Hotel', models.CharField(max_length=150, verbose_name='name hotel')),
                ('Address_Hotel', models.CharField(max_length=300, verbose_name='address hotel')),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='relize_date',
            field=models.DateField(default=datetime.date(2023, 4, 6), verbose_name='relize'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_Room', models.CharField(max_length=150, verbose_name='name room')),
                ('Capacity', models.IntegerField(max_length=2, verbose_name='capacity')),
                ('Type_Room', models.CharField(max_length=50, verbose_name='type room')),
                ('Hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.hotel', verbose_name='Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='PivotTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepartureDate', models.DateField(default=datetime.date(2023, 4, 6), verbose_name='relize')),
                ('ArrivalDate', models.DateField(default=None, verbose_name='relize')),
                ('Client', models.ManyToManyField(to='book.client', verbose_name='Client')),
                ('Hotel', models.ManyToManyField(to='book.hotel', verbose_name='Hotel')),
                ('Room', models.ManyToManyField(to='book.room', verbose_name='Room')),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=20, verbose_name='last name')),
                ('first_name', models.CharField(max_length=20, verbose_name='first name')),
                ('mid_name', models.CharField(blank=True, max_length=20, verbose_name='mid name')),
                ('Post', models.CharField(max_length=20, verbose_name='post')),
                ('POR', models.CharField(max_length=300, verbose_name='places of residence')),
                ('Tel', models.CharField(max_length=20, verbose_name='telephone')),
                ('Hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.hotel', verbose_name='Hotel')),
            ],
        ),
    ]
