# Generated by Django 4.1.4 on 2023-04-20 02:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_client_hotel_alter_book_relize_date_room_pivottable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='employees',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': 'Отель', 'verbose_name_plural': 'Отели'},
        ),
        migrations.AlterModelOptions(
            name='pivottable',
            options={'verbose_name': 'Бронь', 'verbose_name_plural': 'Брони'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Номер', 'verbose_name_plural': 'Номера'},
        ),
        migrations.RenameField(
            model_name='client',
            old_name='first_name',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='last_name',
            new_name='Last_Name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='mid_name',
            new_name='Mid_Name',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='first_name',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='last_name',
            new_name='Last_Name',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='mid_name',
        ),
        migrations.AlterField(
            model_name='employees',
            name='Hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.hotel', verbose_name='hotel'),
        ),
        migrations.AlterField(
            model_name='pivottable',
            name='DepartureDate',
            field=models.DateField(default=datetime.date(2023, 4, 20), verbose_name='relize'),
        ),
        migrations.AlterField(
            model_name='room',
            name='Hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.hotel', verbose_name='hotel'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AddField(
            model_name='employees',
            name='Mid_Name',
            field=models.CharField(blank=True, max_length=20, verbose_name='mid name'),
        ),
    ]
