# Generated by Django 4.1.4 on 2023-05-11 03:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0003_remove_book_author_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user_id',
            field=models.OneToOneField(default=25, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pivottable',
            name='DepartureDate',
            field=models.DateField(default=datetime.date(2023, 5, 11), verbose_name='relize'),
        ),
    ]
