# Generated by Django 4.1.4 on 2023-05-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_client_user_id_alter_pivottable_departuredate'),
    ]

    operations = [
        migrations.AddField(
            model_name='pivottable',
            name='Final_price',
            field=models.IntegerField(default=25, verbose_name='final'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='Price',
            field=models.IntegerField(default=25, max_length=6, verbose_name='price'),
            preserve_default=False,
        ),
    ]
